Camera:
  wb20x:
  - 1.5
  - 1.0
  - 1.164
  wb50x:
  - 2.1797
  - 1.0
  - 1.3711
  wbone:
  - 1.5
  - 1.0
  - 1.164
  像素标定20x: 0.00022
  像素标定50x: 0.000126
  单镜头标定: 0.000221
  RotateImageAngle: 90
Device:
  cameranumber: 1
  loaderflage: false
  microscope: true
ImageSaver:
  imagequailty: 100
  imagestitchsize: 320
  maxworkers: 4
  newimage: 640
  pixelformat: png
  queuenumber: 625
  savepath: C:/Users/12933/Desktop/sAVE2
Loader:
  box1startxz:
  - 159.4
  - 126.35
  box2startxz:
  - 210.05
  - 126.35
  box3startxz:
  - 259.95
  - 126.35
  box4startxz:
  - 310.25
  - 126.35
  boxxgap: 50.0
  boxzgap: 3.5
  cameraexposure: -4
  cameraindex: 0
  rectanglex1: 510
  rectanglex2: 1170
  rectangley1: 500
  rectangley2: 925
  slidepush: 1000.0
  slidereturn: 0.0
  xavoid: 6.0
  xend: 34.3
  zcamera: 50.0
  zend: 103.05
  zlift: 4.0
  串口: COM3
Microscope:
  xend: 57.0
  yend: 32.1
  串口: COM3
  单镜头扫描中心xy:
  - 31.91
  - 36.681
  对焦倍数:
  - 20X
  - 单镜头
  对焦分辨率: 0.003
  对焦方式: 快速扫描二
  对焦步数: 60
  对焦经验值20x: 0.5
  对焦经验值50x: 0.5
  对焦经验值单镜头: 0.911
  玻片扫描中心xy20x:
  - 32.0
  - 43.6
  玻片扫描中心xy50x:
  - 13.0
  - 29.5
  玻片扫描区域宽度: 20
  玻片扫描区域高度: 20
  隔点对焦步长: 5
Task:
  box:
  - 1
  - 2
  - 3
  - 4
  slidenumber: '30'
